### ISSUE TITLE
Is that ready to work with Drupal8

### ISSUE THREAD

**Issue by mahbubulislam** [bradjones1/saml_idp#1]
Hello Brad
I came through this Drupal project https://www.drupal.org/project/saml_idp and found you as a maintainer of this project. Is that ready to use with D8 + simplesamlphp + drupalauth module?

**Comment by bradjones1** [comment]
There is a D8 branch and I just published a -dev release to show on the project page on drupal.org, though I think it takes a while to appear. But yes, this is a D8 module.
