### ISSUE TITLE
How to instantiate sspmod_drupalauth_Auth_Source_External class outside docroot

### ISSUE THREAD

**Issue by brooke-heaton** [bradjones1/saml_idp#2]
We have our vendor directory at project root - as a sibling to vendor - but must use a require function to instantiate the sspmod_drupalauth_Auth_Source_External class within our simplesamlphp/config/config.php file. Is this the expected configuration? I am not clear on whether the class should be autoloading from within the module directory through some other configuration

`require __DIR__ .'/../../../docroot/modules/contrib/saml_idp/src/Auth/Source/External.php';`

**Comment by bradjones1** [comment]
If you install both SSP and this module with composer.json, they will share the autoloader. You do not need a separate require statement. See the first developer note in the README.
