### ISSUE TITLE
Worth clarification within readme

### ISSUE THREAD

**Issue by ryanissamson** [bradjones1/saml_idp#4]
Thanks for the module! This module uses the SP-initiated workflow, correct? If so, it would be worth adding that within the Readme so that it's clear for those building a setup that is IDP-initiated, as I don't think this module would offer much help in that regard.

Let me know if that's not the case though and thanks again for the work on this!

**Comment by JamesSCV** [comment]
Any idea how this could be extended to allow IDP-initiated?

**Comment by bradjones1** [comment]
@ryanissamson This module only sets Drupal up to serve as an IdP, the specific workflow you want to implement in SSP is up to you.

@JamesSCV At the moment I don't have any bandwidth to do much beyond updates related to my specific use cases on this module, if you'd like to submit PR's or sponsor development, I'm open to either/both.

**Comment by JamesSCV** [comment]
@ryanissamson It actually seems like it does support IDP initiated. Seems like it can be managed by placing a link on your idp site that goes to the simplesaml idp. For example I successfully did IDP initiated against the test SP https://sptest.iamshowcase.com/instructions with the following link on my site.
`<a href="https://{your idp domain}.com/simplesaml/saml2/idp/SSOService.php?spentityid=IAMShowcase&RelayState=black">IAMShowcase test Black</a>`
