### ISSUE TITLE
PHP Fatal error: Cannot redeclare class sspmod_drupalauth_Auth_Source_External in /docroot/modules/contrib/saml_idp/src/Auth/Source/External.php

### ISSUE THREAD

**Issue by brooke-heaton** [bradjones1/saml_idp#6]
I'm a bit unclear on what might be wrong with my configuration. I'm now using the contrib saml_idp module but see that the `saml_idp/src/Auth/Source/External.php` is not namespaced and is thus throwing this error. Have I missed a step?

**Comment by bradjones1** [comment]
I'm not particularly sure what the specific error would be in your install, and unfortunately I don't have the ability to provide free support for the module. If you're interested in a consulting engagement, please reach out privately. Or perhaps someone else might be able to chime in. Sorry I can't be more help at the moment.

**Comment by brooke-heaton** [comment]
I'm pretty certain any non-namespaced class will throw this error in D8.

**Comment by bradjones1** [comment]
@brooke-heaton I'm using this in D8, and much of SSP has non-namespaced classes, so that's likely not the issue.

**Comment by brooke-heaton** [comment]
Gotcha. I'll keep digging. I think this may have to do with switching between a custom module and the contrib module now on drupal.org.

**Comment by brooke-heaton** [comment]
Nope. It's still a problem. Unclear on where that error is coming from. I'll report back if I can find the source.
