### ISSUE TITLE
Issues using this as IdP for Moodle SP

### ISSUE THREAD

**Issue by logicexpertise** [bradjones1/saml_idp#7]
I'm having difficulty with using this module as the IdP for a Moodle SP (I've used  the Moodle SAML auth modules at https://github.com/catalyst/moodle-auth_saml2 and https://github.com/dmirandaa/moodle-auth_saml2sso). Hitting Moodle's login page correctly sends the user to Drupal for authentication.

The difficulties I'm having are:

1. After authentication, the user is not returned to the Moodle site. 
2. After authentication, typing the Moodle site URL directly into the browser sends the user back to Drupal.
3. Clicking a Moodle URL embedded within Druapl, always returns the user to Drupal.

Both sites are installed in separate sub-directories of the same base url, i.e. https://base.url.com/drupal and base.url.com/moodle

Also, the behaviour is the same when I use this module as the IdP for the SimpleSAML test SP.

Any insight as to what I might be doing wrong is appreciated.

**Comment by bradjones1** [comment]
Hi @logicexpertise, I apologize but I do not have availability to provide free support in the issue queue; if you would like a quote for consulting, please e-mail me at the address on my profile, or perhaps someone else will chime in here as they have time. Thanks.

**Comment by logicexpertise** [comment]
Hi @bradjones1, I emailed you at the address on your profile before posting here. Perhaps it went into your spam folder?
